### PR TITLE
shuffleArray now returns really shuffled arrays only

### PR DESCRIPTION
**Pull request by sbab**
Except for the impossible edge cases ;)
As requested by #55. Happy Hacktoberfest!

### CODE REVIEW

**Comment by chronoDave** [comment]
Interesting function, but probably too expensive for me to make use of. Most likely going to use a Knuth Shuffle, but since this is such a minor problem, I haven't been around implementing it

**Comment by chronoDave** [comment]
Might be worthwhile to write a performance test, actually.

**Comment by sbab** [comment]
At first glance, Knuth shuffle should be faster by O(nlogn)... gonna implement that and make a quick performance test

**Comment by sbab** [comment]
Done. As expected, the Knuth Shuffle algorithm performs much better than the old one, even thought for arrays of length < 10000 there should be no real difference...

Here's the times I measured, in milliseconds, for 10 shuffles with both algs:

image

And here's the script that generated that: [shufflePerformanceTest.zip](https://github.com/chronoDave/Doombox/files/3693693/shufflePerformanceTest.zip)

**Comment by chronoDave** [comment]
Amazing work, thank you!

**Pull request merged**
